# Generated by Django 4.1.1 on 2023-02-13 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pythonmeaning'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=1000)),
                ('answer', models.TextField()),
                ('interview_question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.interviewquestiontype')),
            ],
        ),
    ]
