# Generated by Django 4.1.1 on 2023-02-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_interviewquestiontype_interviewquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=1000)),
                ('answer', models.TextField()),
            ],
        ),
    ]
