# Generated by Django 4.1.1 on 2023-02-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_randomquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestions',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
