# Generated by Django 4.1.1 on 2023-02-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_interviewquestions_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestions',
            name='img',
            field=models.ImageField(blank=True, upload_to='productImages'),
        ),
    ]
