# Generated by Django 4.1.1 on 2023-03-10 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_interviewquestions_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestions',
            name='question',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='randomquestions',
            name='question',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='SQLquestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=255)),
                ('img', models.ImageField(blank=True, upload_to='productImages')),
                ('answer', models.TextField()),
                ('interview_question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.interviewquestiontype')),
            ],
        ),
    ]
