# Generated by Django 4.1.1 on 2023-03-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_interviewquestions_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomquestions',
            name='img',
            field=models.ImageField(blank=True, upload_to='productImages'),
        ),
    ]
