# Generated by Django 4.1.1 on 2023-03-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_randomquestions_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonmeaning',
            name='img',
            field=models.ImageField(blank=True, upload_to='productImages'),
        ),
        migrations.AddField(
            model_name='pythonmeaning',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
