# Generated by Django 4.1.1 on 2023-03-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_pythonmeaning_img_pythonmeaning_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonmeaning',
            name='pdf',
            field=models.FileField(blank=True, upload_to='pdfs'),
        ),
    ]
