# Generated by Django 4.1.1 on 2023-07-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_sqlquestions_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='productImages')),
                ('url', models.URLField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, upload_to='pdfs')),
            ],
        ),
    ]
