# Generated by Django 4.1.1 on 2023-07-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_sqldetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqldetails',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
