# Generated by Django 4.1.1 on 2023-07-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_sqldetails_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqldetails',
            name='img2',
            field=models.ImageField(blank=True, upload_to='productImages'),
        ),
        migrations.AddField(
            model_name='sqldetails',
            name='img3',
            field=models.ImageField(blank=True, upload_to='productImages'),
        ),
    ]
